In [35]:
import numpy as np
import pandas as pd

import matplotlib # Para ver la versión
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
print(f"numpy=={np.__version__}")
print(f"pandas=={pd.__version__}")
print(f"matplotlib=={matplotlib.__version__}")
print(f"seaborn=={sns.__version__}")

numpy==1.26.4
pandas==2.2.2
matplotlib==3.10.0
seaborn==0.13.2

In [37]:
df = pd.read_csv("madrid_rental_properties_details.csv")

df

,url,property_native_id,rent_eur_per_month,barrio,distrito,latitude,longitude,listing_type,scrape_status,scraped_timestamp,...,Superficie solar,Superficie útil,Teléfono,Terraza,Tipo de casa,Tipo suelo,Trastero,Urbanizado,Vidrios dobles,page_source
0,https://www.pisos.com/alquilar/atico-salamanca...,5.174066e+10,10000.0,Castellana,Salamanca,"40,4342811","-3,6862864",rental,Success,2025-05-28T19:53:30.586256,...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,1
1,https://www.pisos.com/alquilar/atico-rio_rosas...,5.423369e+10,1450.0,Río Rosas,Chamberí,"40,4386119","-3,6999008",rental,Success,2025-05-28T19:53:32.370621,...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,1
2,https://www.pisos.com/alquilar/piso-salamanca_...,5.423565e+10,2200.0,Castellana,Salamanca,"40,4352372","-3,6835148",rental,Success,2025-05-28T19:53:34.120400,...,NaN,100 m²,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,https://www.pisos.com/alquilar/piso-fuente_del...,5.752243e+08,1700.0,Fuente del Berro,Salamanca,40.4290471,-3.6664739,rental,Success,2025-05-28T19:53:35.912036,...,NaN,50 m²,NaN,True,NaN,Grés,NaN,NaN,NaN,1
4,https://www.pisos.com/alquilar/piso-justicia_c...,5.252461e+10,2650.0,Justicia-Chueca,Centro,40.4226065,-3.6991962,rental,Success,2025-05-28T19:53:37.641884,...,NaN,77 m²,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,https://www.pisos.com/alquilar/chalet_pareado-...,1.036083e+07,4300.0,NaN,NaN,"40,516174012","-3,640805874",rental,Success,2025-05-28T20:58:10.540537,...,NaN,270 m²,NaN,Solarium,NaN,NaN,NaN,NaN,NaN,73
2185,https://www.pisos.com/alquilar/chalet_adosado-...,3.839881e+10,6000.0,NaN,NaN,"40,516125912","-3,640196987",rental,Success,2025-05-28T20:58:12.307336,...,NaN,270 m²,NaN,NaN,NaN,Tarima flotante,NaN,True,True,73
2186,https://www.pisos.com/alquilar/chalet_unifamil...,9.417805e+10,6000.0,NaN,NaN,"40,5211707","-3,6484008",rental,Success,2025-05-28T20:58:14.052258,...,355 m²,350 m²,NaN,NaN,NaN,Mármol,NaN,NaN,True,73
2187,https://www.pisos.com/alquilar/piso-el_soto_de...,5.092987e+10,5500.0,NaN,NaN,"40,5198911","-3,64234",rental,Success,2025-05-28T20:58:15.822177,...,NaN,250 m²,NaN,Orientada al sur,NaN,NaN,True,NaN,True,73
2188,https://www.pisos.com/alquilar/piso-la_moralej...,5.425132e+10,4750.0,NaN,NaN,"40,5070505","-3,624863",rental,Success,2025-05-28T20:58:17.572090,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2189 entries, 0 to 2188
Data columns (total 64 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   url                                         2189 non-null   object
 1   property_native_id                          2185 non-null   float64
 2   rent_eur_per_month                          2185 non-null   float64
 3   barrio                                      2155 non-null   object
 4   distrito                                    2155 non-null   object
 5   latitude                                    2189 non-null   object
 6   longitude                                   2189 non-null   object
 7   listing_type                                2189 non-null   object
 8   scrape_status                               2189 non-null   object
 9   scraped_timestamp                           2189 non-null   object
 10  description                                 2185 non-null   object
 11  energy_certificate_main_classification      2185 non-null   object
 12  energy_consumption_rating                   652 non-null    object
 13  energy_consumption_value                    652 non-null    object
 14  energy_emissions_rating                     652 non-null    object
 15  energy_emissions_value                      652 non-null    object
 16  Adaptado a personas con movilidad reducida  134 non-null    object
 17  Agua                                        307 non-null    object
 18  Aire acondicionado                          1252 non-null   object
 19  Amueblado                                   1223 non-null   object
 20  Antigüedad                                  991 non-null    object
 21  Armarios empotrados                         1347 non-null   object
 22  Ascensor                                    1612 non-null   object
 23  Balcón                                      238 non-null    object
 24  Baños                                       2112 non-null   float64
 25  Calefacción                                 1258 non-null   object
 26  Calle alumbrada                             3 non-null      object
 27  Calle asfaltada                             3 non-null      object
 28  Carpintería exterior                        251 non-null    object
 29  Carpintería interior                        50 non-null     object
 30  Chimenea                                    30 non-null     object
 31  Cocina equipada                             1475 non-null   object
 32  Comedor                                     365 non-null    object
 33  Conservación                                1297 non-null   object
 34  Exterior                                    1027 non-null   object
 35  Garaje                                      472 non-null    object
 36  Gas                                         239 non-null    object
 37  Gastos de comunidad                         117 non-null    object
 38  Habitaciones                                2019 non-null   float64
 39  Interior                                    154 non-null    object
 40  Jardín                                      296 non-null    object
 41  Lavadero                                    300 non-null    object
 42  Luz                                         128 non-null    object
 43  No se aceptan mascotas                      142 non-null    object
 44  Orientación                                 527 non-null    object
 45  Piscina                                     363 non-null    object
 46  Planta                                      1637 non-null   object
 47  Portero automático                          174 non-null    object
 48  Puerta blindada                             255 non-null    object
 49  Referencia                                  2185 non-null   object
 50  Se aceptan mascotas                         353 non-null    object
 51  Sistema de seguridad                        101 non-null    object
 52  Soleado                                     208 non-null    object
 53  Superficie construida                       2178 non-null   object
 54  Superficie solar                            26 non-null     object
 55  Superficie útil                             839 non-null    object
 56  Teléfono                                    27 non-null     object
 57  Terraza                                     591 non-null    object
 58  Tipo de casa                                5 non-null      object
 59  Tipo suelo                                  456 non-null    object
 60  Trastero                                    328 non-null    object
 61  Urbanizado                                  6 non-null      object
 62  Vidrios dobles                              201 non-null    object
 63  page_source                                 2189 non-null   int64
dtypes: float64(4), int64(1), object(59)
memory usage: 1.1+ MB

In [39]:
# Función para categorizar el tipo de inmueble
def categorizar_inmueble(description):
    if pd.isna(description):
        return 'Otro'
    description = description.lower()
    if 'piso' in description:
        return 'Piso'
    elif 'casa' in description:
        return 'Casa'
    elif 'chalet' in description:
        return 'Chalet'
    elif 'adosado' in description or 'adosada' in description:
        return 'Adosado'
    elif 'unifamiliar' in description:
        return 'Unifamiliar'
    else:
        return 'Otro'


df['tipo_inmueble'] = df['description'].apply(categorizar_inmueble)

print(df['tipo_inmueble'].value_counts())

tipo_inmueble
Piso       1199
Otro        642
Casa        321
Chalet       26
Adosado       1
Name: count, dtype: int64

In [40]:
df.columns

Index(['url', 'property_native_id', 'rent_eur_per_month', 'barrio', 'distrito',
       'latitude', 'longitude', 'listing_type', 'scrape_status',
       'scraped_timestamp', 'description',
       'energy_certificate_main_classification', 'energy_consumption_rating',
       'energy_consumption_value', 'energy_emissions_rating',
       'energy_emissions_value', 'Adaptado a personas con movilidad reducida',
       'Agua', 'Aire acondicionado', 'Amueblado', 'Antigüedad',
       'Armarios empotrados', 'Ascensor', 'Balcón', 'Baños', 'Calefacción',
       'Calle alumbrada', 'Calle asfaltada', 'Carpintería exterior',
       'Carpintería interior', 'Chimenea', 'Cocina equipada', 'Comedor',
       'Conservación', 'Exterior', 'Garaje', 'Gas', 'Gastos de comunidad',
       'Habitaciones', 'Interior', 'Jardín', 'Lavadero', 'Luz',
       'No se aceptan mascotas', 'Orientación', 'Piscina', 'Planta',
       'Portero automático', 'Puerta blindada', 'Referencia',
       'Se aceptan mascotas', 'Sistema de seguridad', 'Soleado',
       'Superficie construida', 'Superficie solar', 'Superficie útil',
       'Teléfono', 'Terraza', 'Tipo de casa', 'Tipo suelo', 'Trastero',
       'Urbanizado', 'Vidrios dobles', 'page_source', 'tipo_inmueble'],
      dtype='object')

In [41]:
# 1. Limpiar nombres de columnas: eliminar espacios y estandarizar todo en minúsculas
df.columns = (df.columns.str.strip().str.lower())

# 2. Reemplazar comas por puntos en todas las celdas de tipo string
df = df.applymap(lambda x: x.replace(',', '.') if isinstance(x, str) else x)

# 3. Función para limpiar y convertir superficies a float
def limpiar_superficie(col):
    return pd.to_numeric(
        df[col].astype(str).str.replace(' m²', '', regex=False).str.replace(',', '.'),
        errors='coerce'
    )

df['superficie construida'] = limpiar_superficie('superficie construida')
df['superficie útil'] = limpiar_superficie('superficie útil')


# 4. Normalizar columna planta
def normalizar_planta(planta):
    if pd.isna(planta):
        return planta
    planta = str(planta).strip().lower()
    if "semisótano" in planta or "entresuelo" in planta or "sótano" in planta:
        return -1
    if "principal" in planta or "bajo" in planta:
        return 0
    if "más de 20" in planta:
        return 20
    planta = planta.replace("ª", "").replace("º", "")
    try:
        return int(planta)
    except ValueError:
        return planta  

df["planta"] = df["planta"].apply(normalizar_planta)

# 5. Intentar convertir todas las columnas a float (si aplica)
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col], errors='ignore')
    except:
        pass  # Ignora columnas que no pueden convertirse

# 6. Eliminar filas duplicadas
df.drop_duplicates(inplace=True)

# 7. Eliminar columnas completamente vacías
df.dropna(axis=1, how='all', inplace=True)

# 8. Reiniciar índice ---
df.reset_index(drop=True, inplace=True)

df

C:\Users\morgo\AppData\Local\Temp\ipykernel_2096\2399255407.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.replace(',', '.') if isinstance(x, str) else x)
C:\Users\morgo\AppData\Local\Temp\ipykernel_2096\2399255407.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')

,url,property_native_id,rent_eur_per_month,barrio,distrito,latitude,longitude,listing_type,scrape_status,scraped_timestamp,...,superficie útil,teléfono,terraza,tipo de casa,tipo suelo,trastero,urbanizado,vidrios dobles,page_source,tipo_inmueble
0,https://www.pisos.com/alquilar/atico-salamanca...,5.174066e+10,10000.0,Castellana,Salamanca,40.434281,-3.686286,rental,Success,2025-05-28T19:53:30.586256,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,1,Otro
1,https://www.pisos.com/alquilar/atico-rio_rosas...,5.423369e+10,1450.0,Río Rosas,Chamberí,40.438612,-3.699901,rental,Success,2025-05-28T19:53:32.370621,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,1,Piso
2,https://www.pisos.com/alquilar/piso-salamanca_...,5.423565e+10,2200.0,Castellana,Salamanca,40.435237,-3.683515,rental,Success,2025-05-28T19:53:34.120400,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Piso
3,https://www.pisos.com/alquilar/piso-fuente_del...,5.752243e+08,1700.0,Fuente del Berro,Salamanca,40.429047,-3.666474,rental,Success,2025-05-28T19:53:35.912036,...,50.0,NaN,True,NaN,Grés,NaN,NaN,NaN,1,Piso
4,https://www.pisos.com/alquilar/piso-justicia_c...,5.252461e+10,2650.0,Justicia-Chueca,Centro,40.422607,-3.699196,rental,Success,2025-05-28T19:53:37.641884,...,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Piso
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,https://www.pisos.com/alquilar/chalet_pareado-...,1.036083e+07,4300.0,NaN,NaN,40.516174,-3.640806,rental,Success,2025-05-28T20:58:10.540537,...,270.0,NaN,Solarium,NaN,NaN,NaN,NaN,NaN,73,Casa
2185,https://www.pisos.com/alquilar/chalet_adosado-...,3.839881e+10,6000.0,NaN,NaN,40.516126,-3.640197,rental,Success,2025-05-28T20:58:12.307336,...,270.0,NaN,NaN,NaN,Tarima flotante,NaN,1.0,True,73,Chalet
2186,https://www.pisos.com/alquilar/chalet_unifamil...,9.417805e+10,6000.0,NaN,NaN,40.521171,-3.648401,rental,Success,2025-05-28T20:58:14.052258,...,350.0,NaN,NaN,NaN,Mármol,NaN,NaN,True,73,Chalet
2187,https://www.pisos.com/alquilar/piso-el_soto_de...,5.092987e+10,5500.0,NaN,NaN,40.519891,-3.642340,rental,Success,2025-05-28T20:58:15.822177,...,250.0,NaN,Orientada al sur,NaN,NaN,True,NaN,True,73,Piso
2188,https://www.pisos.com/alquilar/piso-la_moralej...,5.425132e+10,4750.0,NaN,NaN,40.507050,-3.624863,rental,Success,2025-05-28T20:58:17.572090,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73,Piso

In [42]:
# Rellenar NaN en superficie útil con el valor de superficie construida
df['superficie útil'] = df['superficie útil'].fillna(df['superficie construida'])

# Función para rellenar baños si es NaN
def rellenar_banos(row):
    if pd.isna(row['baños']):
        if not pd.isna(row['superficie construida']):
            return max(1, round(row['superficie construida'] / 70)) 
        else:
            return 1   # Al menos 1 baño
    else:
        return int(row['baños'])

df['baños'] = df.apply(rellenar_banos, axis=1)

import numpy as np

# Función para imputar habitaciones según superficie útil
def estimar_habitaciones(row):
    if pd.isna(row['habitaciones']):
        if not pd.isna(row['superficie útil']):
            sup = row['superficie útil']
            if sup < 50:
                return 1
            else:
                return int(np.floor(sup / 25))
        else:
            return np.nan  # Si tampoco hay superficie útil, no se puede estimar
    else:
        return row['habitaciones']

df['habitaciones'] = df.apply(estimar_habitaciones, axis=1)

In [43]:
# Columnas con más del 80% de nulos
nulls = df.isnull().mean().sort_values(ascending=False)
print(nulls[nulls > 0.80])

calle alumbrada                               0.998630
calle asfaltada                               0.998630
tipo de casa                                  0.997716
urbanizado                                    0.997259
superficie solar                              0.988122
teléfono                                      0.987666
chimenea                                      0.986295
carpintería interior                          0.977159
sistema de seguridad                          0.953860
gastos de comunidad                           0.946551
luz                                           0.941526
adaptado a personas con movilidad reducida    0.938785
no se aceptan mascotas                        0.935130
interior                                      0.929648
portero automático                            0.920512
vidrios dobles                                0.908177
soleado                                       0.904979
balcón                                        0.891275
gas                                           0.890818
carpintería exterior                          0.885336
puerta blindada                               0.883508
jardín                                        0.864778
lavadero                                      0.862951
agua                                          0.859753
trastero                                      0.850160
se aceptan mascotas                           0.838739
piscina                                       0.834171
comedor                                       0.833257
dtype: float64

In [44]:
# Se eliminan las columnas que no aportan información

columns_to_drop = ['url', 'property_native_id', 'scrape_status', 'scraped_timestamp', 'page_source', 'listing_type'
                   'referencia', 'description', 'energy_certificate_main_classification', 'energy_consumption_value',
                    'energy_emissions_value', 'luz', 'no se aceptan mascotas', 'urbanizado', 'calle asfaltada',
                    'calle alumbrada', 'tipo de casa', 'luz', 'se aceptan mascotas', 'superficie solar', 'teléfono',
                    'carpintería interior', 'interior', 'agua', 'soleado', 'carpintería exterior', 'tipo suelo',
                     'gastos de comunidad',  'gas', 'lavadero', 'comedor', 'orientación', 'armarios empotrados']

df.drop(columns=[col for col in columns_to_drop if col in df.columns], inplace=True)

In [45]:
# Sustituir NaN por 0 en las columnas indicadas
columnas_a_llenar_cero = ['adaptado a personas con movilidad reducida', 'planta']

for col in columnas_a_llenar_cero:
    if col in df.columns:
        df[col].fillna(0, inplace=True)


# Sustituir NaN por False en las columnas indicadas 
columnas_a_llenar_false = ['amueblado', 'energy_consumption_rating', 'energy_emissions_rating', 'aire acondicionado',
                           'calefacción', 'cocina equipada', 'garaje', 'exterior', 'trastero', 'ascensor', 'terraza',
                           'balcón', 'chimenea', 'piscina', 'jardín', 'vidrios dobles', 'sistema de seguridad', 
                           'puerta blindada', 'portero automático']

for col in columnas_a_llenar_false:
    if col in df.columns:
        df[col].fillna(False, inplace=True)


df['conservación'] = df['conservación'].fillna('En buen estado')

C:\Users\morgo\AppData\Local\Temp\ipykernel_2096\2161950264.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(0, inplace=True)
C:\Users\morgo\AppData\Local\Temp\ipykernel_2096\2161950264.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(False, inplace=True)
C:\Users\morgo\AppData\Local\Temp\ipykernel_2096\2161950264.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[col].fillna(False, inplace=True)

In [46]:
# Se convierten en booleanas las siguientes columnas:

valores_terraza = {'19 metros', 'No acristalada',
       'Gran mirador para 2 sillas y una mesita.', '24m²',
       'Con vistas al retiro', '2 terrazas', '10', 'mtrs=25',
       'Dos terrazas de 60 m² cada uno', '3 terrazas', '80 metros',
       'Pequeña pero muy mona', 'mtrs=0', '20 m²',
       'En una de las habitaciones', '30 m²', 'De unos 8m²',
       'De unos 15m²', '3m²', 'De 30 m². con toldo y luces',
       'En azotea con vistas de madrid', 'En azotea', 'Mas de 18m²',
       'Terraza-patio ajardinado de uso privativo', 'De unos 10m²',
       '15 m²', '6m²', 'De 40 m².', '30m²',
       '2 balcones + una terraza interior', 'En el dormitorio', '5',
       '3 m²', 'Balcones', '100', '6', 'Y un mirador', 'mtrs=8', 'mtrs=5',
       '20', 'Acristalada', '4', '12', '8', '13', '3', '15', '60', '7',
       '15.00 m²', 'Acristalda', 'Con espacio para mesa y tumbonas',
       'Una a pie de salón y otra amplia en planta alta.', 'Solarium',
       'Orientada al sur'}
df['terraza'] = df['terraza'].isin(valores_terraza)

valores_piscina = {'Propia', 'Comunitaria', 'Privada'}
df['piscina'] = df['piscina'].isin(valores_piscina)

valores_trastero ={'Opcional', 'Dentro de la casa', '8m². sótano-1 puerta 10'}
df['trastero'] = df['trastero'].isin(valores_trastero)

valores_calefacción = {'Eléctrica', 'Individual eléctrica', 'Central',
       'Gas natural', 'Individual', 'Aerotermia',
       'Contadores individuales', 'Gasoil', 'Bomba de calor',
       'Incluida en la renta', 'Con contadores individuales',
       'Suelo radiante', 'Bomba frio calor', 'Con contador individual',
       'Central con contador individual', 'Bomba friol calor',
       'Gasoil con contador individual'}
df['calefacción'] = df['calefacción'].isin(valores_calefacción)

valores_ascensor = {'3', '2', 'Precioso de madera', 'Dos ascensores',
       '3 ascensores', 'En la entre-planta.'}
df['ascensor'] = df['ascensor'].isin(valores_ascensor)

valores_aire_acondicionado = {'Frío y calor', 'Frío', 'Individual',
       'Splits y unidades', 'A/a f/c', 'Comunitario', 'Aerotermia',
       'Frío-calor', 'Con bomba de calor', 'Centralizado',
       'A/a por conductos con sistema airzone', 'Tambien suelo radiante',
       'A/a f/c centralizado', 'En toda la casa', 'De ventana',
       'Por conductos independientes', 'Por conductos'}
df['aire acondicionado'] = df['aire acondicionado'].isin(valores_aire_acondicionado)

valores_exterior = {'Exterior calle',
       'Preciosa vistas a patio de manzana.', 'Exterior',
       'A piscina y calle', 'Ladrillo', 'Con vistas al retiro',
       'Con un balcón', 'Exterior patio manzana'}
df['exterior'] = df['exterior'].isin(valores_exterior)

valores_garaje ={'1', '2', 'Más de 2'}
df['garaje'] = df['garaje'].isin(valores_garaje)

valores_jardín = {'Privado', 'Comunitario'}
df['jardín'] = df['jardín'].isin(valores_jardín)

valores_sistema_seguridad = {'con cámaras de seguridad', 'Portero físico',
       'Cámara en todo el edificio', '12 horas/día los 7 días/semana.',
       'vigilancia 24h. con cámaras de seguridad', 'Videovigilancia',
       'Portero', 'Conserje. Doble portal', 'Conserje',
       'Portero residente', '24 horas', 'Portería incluso domingos',
       'Conserje residente', 'Vigilancia 24 horas', '24hs.'}
df['sistema de seguridad'] = df['sistema de seguridad'].isin(valores_sistema_seguridad)

valores_vidrios_dobles = {'Esta muy aislado', 'Rotura puente térmico',
       'Climalit con rotura puente térmico', 'Climalit'}
df['vidrios dobles'] = df['vidrios dobles'].isin(valores_vidrios_dobles)

In [47]:
# Categorización amueblado

valores_si = {
    'Completamente amueblado', 'Muebles de diseño', 'De forma minimalista y funcional', 
    'Totalmente', 'Con muebles de diseño', 'Cocina amueblada', 'Completo', 'Moderno y actual'
}

valores_semi = {
    'Solo la cocina y los baños', 'Semi-amueblado', 'Semi amueblado',
    'Opcional amueblado/vacio', 'Puede ser sin amueblar y amueblado',
    'Pueden amueblar la 3ra habitación tambine', 'No muy bien. mala calidad y poco ergonómico.'
}

def categorizar_amueblado(valor):
    if pd.isna(valor):
        return np.nan
    if valor in valores_si:
        return 'Si'
    elif valor in valores_semi:
        return 'Semi'
    elif valor is False or valor == 'False':
        return 'No'
    else:
        return 'Si'  

df['amueblado'] = df['amueblado'].apply(categorizar_amueblado)

In [48]:
# Mostrar valores nulos ordenados (descendente)
df.isnull().sum().sort_values(ascending=False)

antigüedad                                    1198
distrito                                        34
barrio                                          34
superficie construida                           11
superficie útil                                  9
habitaciones                                     6
rent_eur_per_month                               4
referencia                                       4
sistema de seguridad                             0
exterior                                         0
puerta blindada                                  0
terraza                                          0
portero automático                               0
planta                                           0
piscina                                          0
jardín                                           0
trastero                                         0
vidrios dobles                                   0
garaje                                           0
cocina equipada                                  0
conservación                                     0
chimenea                                         0
calefacción                                      0
baños                                            0
balcón                                           0
ascensor                                         0
amueblado                                        0
aire acondicionado                               0
adaptado a personas con movilidad reducida       0
energy_emissions_rating                          0
energy_consumption_rating                        0
listing_type                                     0
longitude                                        0
latitude                                         0
tipo_inmueble                                    0
dtype: int64

In [49]:
df = df.rename(columns = { "latitude": "lat", "longitude": "lon" }) 

df['lat'] = pd.to_numeric(df['lat'], errors='coerce')
df['lon'] = pd.to_numeric(df['lon'], errors='coerce')

In [50]:
df.rename(columns={'rent_eur_per_month': 'price_eur'}, inplace=True)
df.to_csv("madrid_rental_properties_cleaned.csv", index=False)

In [51]:
##############################################################################################################################